/*! Timer in arch layer; use 'arch_timer_t' device defined in configuration */
#pragma once

#include <types/time.h>

/*! interface for kernel  */

/*! Initialize timer 'arch' subsystem: timer device, subsystem data */

void arch_timer_init(timespec_t period, void *kernel_timer_handler);

void arch_timer_set_interval(timespec_t period);

/*! Get minimal timer interval supported by hardware timer */
void arch_get_min_interval(timespec_t *time);

/*! Enable/disable interrupt generated by hardware timer */
void arch_enable_timer_interrupt();
void arch_disable_timer_interrupt();
